bind(
  name = 'gtest',
  actual = '@gtest//:main',
)

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    build_file = "gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)

bind(
  name = "libwebsockets",
  actual = "@libwebsockets//:main",
)

new_git_repository(
    name = "libwebsockets",
    remote = "https://github.com/warmcat/libwebsockets.git",
    build_file = "websocket.BUILD",
    tag = "v2.0.2"
)
