bind(
  name = 'gtest',
  actual = '@gtest//:main',
)

new_http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    build_file = "gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)

bind(
  name = 'websocketpp',
  actual = '@websocketpp//:main',
)

new_http_archive(
    name = "websocketpp",
    url = "https://github.com/zaphoyd/websocketpp/archive/0.7.0.zip",
    build_file = "websocket.BUILD",
    strip_prefix = "websocketpp-0.7.0",
)
